server:
  port: 8092
  servlet: 
    context-path: /sparrow-bpm

spring:
  security:
    oauth2:
      resourceserver:        jwt:          jwk-set-uri: http://localhost:6060/.well-known/jwks.json
        
      client:
        registration:          sparrow-provider:
            client-id: sparrow-bpm
            client-authentication-method: header
            client-secret: password
                    provider:          sparrow-provider: 
            authorization-uri: "https://localhost:6060/oauth/authorize"
            token-uri: "https://localhost:6060/oauth/token"
            user-info-uri: "https://localhost:6060/userinfo"
            user-info-authentication-method: "header"
            jwk-set-uri: "http://localhost:6060/.well-known/jwks.json"
            user-name-attribute: "name"

  data:
    mongodb:
      host: "localhost"
      port: 27017
      database: "kogito"
      
      


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka   #服务eureka的URL地址


#      username: "user"
#      password: "secret"

# security.oauth2.authorizationserver.jwt.enabled: false

#logging:
#  level:
#    root: DEBUG
